version: "2"
services:

  reports:
    image: openlmis/dev:2
    ports:
      - "5005:5005"
      - "8080:8080"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env

  db:
    ports:
      - "5432"

volumes:

  gradlecache:
    external: false
