version: "2"
services:

  builder:
    image: openlmis/dev:2
    links:
      - db
      - log
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env

  image:
    build: .
    image: openlmis-mw/reports

  db:
    image: openlmis/postgres:9.6
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/fulfillment:/var/log'
